### ISSUE TITLE
Discussion opencascade (DLR-SC) vs occt (conda-forge)

### ISSUE THREAD

**Issue by fcollonval** [conda-forge/occt-feedstock#33]
This is not so much an issue but rather a discussion I'ld like to have with people involved with opencascade and its python wrapper.

@rainman110, @looooo you both packaged opencascade 7.4 for conda. But you did it differently.

opencascade 7.4.0 has the following recipe:

```yaml
source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V7_4_0;sf=tgz
  sha256: 9614c2075cef53e30b25317fc8fcfb71d60a69181d562e1c56469ed8e54ad758
  patches:
    - no-xmu.patch     # [linux]
    - fix-private-linking.patch
    - fix_brepblend.patch

build:
  number: 4
  detect_binary_files_with_prefix: True

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - cmake
    - ninja
  host:
    - libglu # [linux]
    - freeimageplus
    - tbb
    - tbb-devel
    - python
    - freetype
    - fontconfig # [unix]

  run:
    - freeimageplus
    - tbb
    - freetype
    - six
```

Versus this package recipe
```yaml
source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=fd47711d682be943f0e0a13d1fb54911b0499c31;sf=tgz
  sha256: af73c89ade0467ca7351dc445e4bd20832387da1e205f6955bc9356ab7d9f22b

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - cmake
    - ninja
  host:
    - freetype
    - fontconfig
    - tbb-devel
    - xorg-libxt  # [linux]
    - xorg-libxmu  # [linux]
  run:
    - freetype
    - fontconfig
    - xorg-libxt  # [linux]
    - xorg-libxmu  # [linux]
```

Questions:
- What are the difference? It seems that in the DLR package, the dependency to XMU has been dropped (why?) and that TBB has been made a private dependency to not make it apparent for instance when packaging `pythonocc-core`.
- Would it be possible to converge on a common recipe?
- Note: it seems that you are not using the same commit of opencascade.
